### ISSUE TITLE
[Chi nhánh EVN] Mô tả chung về lỗi

### ISSUE THREAD

**Issue by aquarius15283** [trvqhuy/nestup_evn#11]
**Mô tả lỗi / Describe the bug**
Không kết nối được đến EVN server để lấy dữ liệu.

**Logs**
Logger: custom_components.nestup_evn.config_flow
Source: custom_components/nestup_evn/nestup_evn.py:342
Integration: EVN Data Fetcher ([documentation](https://github.com/trvqhuy/nestup_evn/), [issues](https://github.com/trvqhuy/nestup_evn/issues))
First occurred: 10:45:16 AM (2 occurrences)
Last logged: 11:23:33 AM
Unexpected exception: Server disconnected

Traceback (most recent call last):
  File "/config/custom_components/nestup_evn/config_flow.py", line 182, in _verify_id
    res = await self._api.request_update(
  File "/config/custom_components/nestup_evn/nestup_evn.py", line 104, in request_update
    fetch_data = await self.request_update_evnhanoi(
  File "/config/custom_components/nestup_evn/nestup_evn.py", line 359, in request_update_evnhanoi
    return await self.request_update_evnhanoi(
  File "/config/custom_components/nestup_evn/nestup_evn.py", line 342, in request_update_evnhanoi
    resp = await self._session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Server (thông tin máy chủ đang chạy HA):**
 - OS: HassOS
 - HA platform: Core
 - HA Version: 2022.11.2

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: v.2.1.0

**Comment by trvqhuy** [comment]
Hello @aquarius15283,

Bạn cho mình xin thêm thông tin về chi nhánh EVN cùng với địa điểm của bạn nhé.
Khả năng cao là do phía server của EVN, không biết bạn đã thử login vào App chính thức của EVN để kiểm tra dữ liệu sản lượng điện tiêu thụ chưa nhỉ?

**Comment by trvqhuy** [comment]
Vì bạn @aquarius15283 đã không cung cấp các thông tin cần thiết để tiếp tục fix lỗi, issue này sẽ được closed tại đây
