### ISSUE TITLE
Lỗi Add device : Unexpected exception importing platform custom_components.nestup_evn.config_flow

### ISSUE THREAD

**Issue by tranngockhanh2303** [trvqhuy/nestup_evn#3]
**Phiên bản cài đặt :**
- Home Assistant 2022.9.2
- Nestup_evn : v2.1.0
**Mô tả :** 
Error occurred loading configuration flow for integration nestup_evn: Exception importing custom_components.nestup_evn.config_flow
Unexpected exception importing platform custom_components.nestup_evn.config_flow

Traceback (most recent call last):
  File "/homeassistant2022/lib/python3.9/site-packages/homeassistant/loader.py", line 681, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/homeassistant2022/lib/python3.9/site-packages/homeassistant/loader.py", line 698, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/.homeassistant/custom_components/nestup_evn/config_flow.py", line 13, in <module>
    from . import nestup_evn
  File "/root/.homeassistant/custom_components/nestup_evn/nestup_evn.py", line 48, in <module>
    from .types import EVN_NAME, VIETNAM_EVN_AREA, Area
  File "/root/.homeassistant/custom_components/nestup_evn/types.py", line 42, in <module>
    class Area:
  File "/root/.homeassistant/custom_components/nestup_evn/types.py", line 46, in Area
    key: str | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Đã xóa phiên bản cũ (bao gồm device và trong hacs) -> restart hass -> cài lại Nestup_evn 2.1.0 -> Add device -> lỗi
Phiên bản 1.2.9 cài đặt bình thường

**Comment by trvqhuy** [comment]
@tranngockhanh2303 mình nghĩ đây là lỗi do environment, có thể sẽ fix được nếu như bạn tự vào file **types.py** sửa tất cả phần có '|' đổi thành 'or', nhưng sẽ không đảm bảo là giải quyết hoàn toàn lỗi do environment này gây ra.

Bạn có thể sửa code của mình theo như mình nói phía trên và cho mình biết kết quả nhé, do khác environment nên mình không thể debug được.

Cho mình xin thêm thông tin về platform HA, và cách cài đặt HA của bạn nhé (thông qua Docker,..) nhé?

**Comment by tranngockhanh2303** [comment]
Chính xác là lỗi declare variable trong types.py, mình có sửa '|' đổi thành 'or' và đã chạy ok. Thanks bro 
Environment mình đang chạy :
- Home Assistant core 2022.9.2
- Environment : Python environment - Python 3.9.13
- Device : Router running Optware : Debian 12 (bookworm) - Architecture : MIPS
