### ISSUE TITLE
Unavailable

### ISSUE THREAD

**Issue by Builder-DE-TH** [trvqhuy/nestup_evn#34]
**Mô tả lỗi / Describe the bug**
Service unavailable

**Logs**
2023-11-03 14:24:56.856 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nestup_evn platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
return await self.update_method()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/nestup_evn/sensor.py", line 123, in _async_update
await self.update()
File "/config/custom_components/nestup_evn/sensor.py", line 82, in update
self._data = await self._api.request_update(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/nestup_evn/nestup_evn.py", line 122, in request_update
fetch_data = await self.request_update_evnhcmc(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/nestup_evn/nestup_evn.py", line 453, in request_update_evnhcmc
resp = await self._session.post(

**Ảnh chụp / Screenshots**
Thêm ảnh chụp để thể hiện lỗi rõ ràng hơn.

**Server (thông tin máy chủ đang chạy HA):**
 - OS: HAOS
 - HA platform: Core
 - HA Version: 2023.11.0
**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: [e.g. HACS] (cách cài đặt Integration)
 - Version: [e.g. v.2.1.0]

**Thông tin thêm**
Thêm những thông tin khác ngoài các thông tin kể trên.

**Comment by Builder-DE-TH** [comment]
Fixed in 11.1
