### ISSUE TITLE
[EVNHCMC] Unexpected error

### ISSUE THREAD

**Issue by nhatnguyen95** [trvqhuy/nestup_evn#36]
**Mô tả lỗi / Describe the bug**
Sau khi nhập Customer ID và dùng số điện thoại, password để đăng nhập

**Logs**
2023-11-29 23:22:01.477 ERROR (MainThread) [custom_components.nestup_evn.config_flow] Unexpected exception: Cannot connect to host cskh.evnhcmc.vn:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/nestup_evn/config_flow.py", line 164, in _try_auth
    res = await self._api.login(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nestup_evn/nestup_evn.py", line 74, in login
    return await self.login_evnhcmc(username, password)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nestup_evn/nestup_evn.py", line 181, in login_evnhcmc
    resp = await self._session.post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host cskh.evnhcmc.vn:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

**Ảnh chụp / Screenshots**
![image](https://github.com/trvqhuy/nestup_evn/assets/16730018/5af1e709-f727-452a-b5e4-da2cc7282376)

**Server (thông tin máy chủ đang chạy HA):**
 - OS: HA Supervisor sử dụng Virtual machine trên DSM 7.2
 - HA Core: 2023.11.3
 - HA Supervisor: 2023.11.6
 - Frontend: 20231030.2

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: 1.33.0

**Comment by xiaomihomeDomo** [comment]
I have same problem

**Comment by trvqhuy** [comment]
Hi @nhatnguyen95, hiện tại cơ sở dữ liệu từ EVNHCMC đang gặp vấn đề, đây là lỗi từ EVNHCMC endpoint, không phải do integration.

Hi @xiaomihomeDomo, currently the database from EVNHCMC is having some critical problems, which leads to empty consumption data. This is an error from the EVNHCMC endpoint, not the integration itself.
