### ISSUE TITLE
[EVN Ha Noi] Không load được dữ liệu

### ISSUE THREAD

**Issue by khaisilk1910** [trvqhuy/nestup_evn#73]
**Mô tả lỗi / Describe the bug**
Bị lỗi không load được dữ liệu sau khi update lên bản mới hôm nay.
Nhờ Tác giả sửa lỗi giúp.
Cảm ơn!

**Logs**
```
Logger: homeassistant.helpers.entity_platform
Source: helpers/entity_platform.py:419
First occurred: 15:00:32 (14 occurrences)
Last logged: 16:54:07

nestup_evn raises exception ConfigEntryNotReady in forwarded platform sensor; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups

```
```
This error originated from a custom integration.

Logger: custom_components.nestup_evn.sensor
Source: helpers/update_coordinator.py:382
integration: EVN Data Fetcher (documentation, issues)
First occurred: 15:00:32 (14 occurrences)
Last logged: 16:54:07

Unexpected error fetching nestup_evn-PD05000140586 data
Unexpected error fetching nestup_evn-PD05000078426 data
Unexpected error fetching nestup_evn-PD05000040043 data
Unexpected error fetching nestup_evn-PD05000030540 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nestup_evn/sensor.py", line 123, in _async_update
    await self.update()
  File "/config/custom_components/nestup_evn/sensor.py", line 96, in update
    login_state = await self._api.login(
                        ^^^^^^^^^^^^^^^^
TypeError: EVNAPI.login() missing 1 required positional argument: 'customer_id'
```

**Ảnh chụp / Screenshots**
![image](https://github.com/user-attachments/assets/edc4bc46-7c35-4b95-8862-0643432d3df8)
![image](https://github.com/user-attachments/assets/ab67f4c2-8cea-4897-8e67-906a855fe286)
![image](https://github.com/user-attachments/assets/953d4215-42d8-4b65-b9c1-07a57d051223)

**Server (thông tin máy chủ đang chạy HA):**
 ![image](https://github.com/user-attachments/assets/920294fe-7e91-48a1-91c7-60d8b31bf05a)

**Integration (thông tin phiên bản Integration đã cài đặt):**
 - Installation method: HACS
 - Version: 2.4.5

**Comment by chautruongthinh** [comment]
> Sau khi xóa đi add lại thì dữ liệu đã load OK. Chỉ có chỉ số Lịch cắt điện bị lỗi. ![image](https://private-user-images.githubusercontent.com/3167468/391498465-be58255e-f28e-42e5-a2f1-e83bf65d20c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzQ1MzcsIm5iZiI6MTczMzEzNDIzNywicGF0aCI6Ii8zMTY3NDY4LzM5MTQ5ODQ2NS1iZTU4MjU1ZS1mMjhlLTQyZTUtYTJmMS1lODNiZjY1ZDIwYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDJUMTAxMDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjJlZjhmNzliNjZkNzc0NmRiYzQzMTIzNmJmYzBjNjY2NjgyNzkwMjYwZWU1NDhlOGI4OWM3ZmM3ZDNmM2E4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Rm2-WTwCBFItCyuMSmc--VrWT7-Dx9AWGyGf5BRxZ8A)

bác inbox giúp mình tk EVN để mình fix nha

**Comment by trvqhuy** [comment]
cảm ơn bạn @chautruongthinh

**Comment by chautruongthinh** [comment]
> cảm ơn bạn @chautruongthinh

bác rảnh thì inbox zalo cho mình phát nha. Mình hỏi bác về vụ EVNNPC

**Comment by vdt2210** [comment]
@trvqhuy mình đang gặp lỗi này mấy bữa nay. EVC HCM

**Comment by ddkvn** [comment]
EVNHCMC sau khi cập nhật lên 2.4.5 lỗi y vậy không load được dữ liệu.

**Comment by khaisilk1910** [comment]
> > Sau khi xóa đi add lại thì dữ liệu đã load OK. Chỉ có chỉ số Lịch cắt điện bị lỗi. ![image](https://private-user-images.githubusercontent.com/3167468/391498465-be58255e-f28e-42e5-a2f1-e83bf65d20c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzQ1MzcsIm5iZiI6MTczMzEzNDIzNywicGF0aCI6Ii8zMTY3NDY4LzM5MTQ5ODQ2NS1iZTU4MjU1ZS1mMjhlLTQyZTUtYTJmMS1lODNiZjY1ZDIwYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDJUMTAxMDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjJlZjhmNzliNjZkNzc0NmRiYzQzMTIzNmJmYzBjNjY2NjgyNzkwMjYwZWU1NDhlOGI4OWM3ZmM3ZDNmM2E4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Rm2-WTwCBFItCyuMSmc--VrWT7-Dx9AWGyGf5BRxZ8A)
> 
> bác inbox giúp mình tk EVN để mình fix nha

Mình ko tìm thấy chỗ Inbox trên Git.

**Comment by vboyhn** [comment]
mình cũng bị lỗi này, kiểu nó bị lỗi chỗ tự động update dữ liệu ấy, lần đầu add thì update ok, sau đó là không update nữa.

**Comment by chautruongthinh** [comment]
> Mình ko tìm thấy chỗ Inbox trên Git.

![IMG_UPLOAD_20241212_132639](https://github.com/user-attachments/assets/4f113623-d864-4df5-930c-34e2612446b9)
Inbox giúp mình

**Comment by chautruongthinh** [comment]
@trvqhuy lỗi đã fix. Close bug này đi
