### ISSUE TITLE
Clear log error

### ISSUE THREAD

**Issue by vietnd87** [trvqhuy/nestup_evn#76]
**Mô tả lỗi / Describe the bug**
Cảm ơn chủ thớt đã viết ra module hữu ích này. Trong quá trình sử dụng mình thấy có 1 số vấn đề như sau:
- Mất kết nối mỗi lần update module
- Log error trong home-assistant.log nhiều lần mỗi ngày. Mong bạn xử lý vấn đề này.

**Logs**
ERROR (MainThread) [custom_components.nestup_evn.sensor] Unexpected error fetching nestup_evn-XXXXXXXXXX data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nestup_evn/sensor.py", line 123, in _async_update
    await self.update()
  File "/config/custom_components/nestup_evn/sensor.py", line 96, in update
    login_state = await self._api.login(
                        ~~~~~~~~~~~~~~~^
        self._area_name, self._username, self._password
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: EVNAPI.login() missing 1 required positional argument: 'customer_id'

**Comment by vietnd87** [comment]
Sorry bạn, Lỗi trên là do đăng nhập sai thông tin. Đăng nhập đúng thì hết. 
Cảm ơn bạn về module này!
